name: Test cloudflared PATH

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: e
        shell: bash
        run: |
          choco install cloudflared -y
          cloudflared --version
