name: Test cloudflared PATH

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - shell: bash
        run: choco install cloudflared -y
      - shell: bash
        run: cloudflared --version
