name: Test Dynamic Step Name

on:
  workflow_dispatch:

jobs:
  remote:
    runs-on: ubuntu-latest

    environment:
      name: 🖥️ Remote Desktop
      url: ${{ steps.step.outputs.url }}

    steps:
      - name: Set output
        id: step
        run: |
          echo "url=https://example.trycloudflare.com" >> "$GITHUB_OUTPUT"
          sleep 10
