name: Test Dynamic Step Name

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set output
        id: step
        run: |
          echo "url=https://example.trycloudflare.com" >> "$GITHUB_OUTPUT"

      - name: 🖥️ ${{ steps.step.outputs.url }}
        run: |
          echo "The URL is ${{ steps.step.outputs.url }}"
